# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messenger/proto/messenger.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'messenger/proto/messenger.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fmessenger/proto/messenger.proto\x12\x08mes_grpc\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\".\n\x0eMessageRequest\x12\x0e\n\x06\x61uthor\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"?\n\x0fMessageResponse\x12,\n\x08sendTime\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"U\n\x07Message\x12\x0e\n\x06\x61uthor\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12,\n\x08sendTime\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\x92\x01\n\x0fMessengerServer\x12\x42\n\x0bSendMessage\x12\x18.mes_grpc.MessageRequest\x1a\x19.mes_grpc.MessageResponse\x12;\n\x0cReadMessages\x12\x16.google.protobuf.Empty\x1a\x11.mes_grpc.Message0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messenger.proto.messenger_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEREQUEST']._serialized_start=107
  _globals['_MESSAGEREQUEST']._serialized_end=153
  _globals['_MESSAGERESPONSE']._serialized_start=155
  _globals['_MESSAGERESPONSE']._serialized_end=218
  _globals['_MESSAGE']._serialized_start=220
  _globals['_MESSAGE']._serialized_end=305
  _globals['_MESSENGERSERVER']._serialized_start=308
  _globals['_MESSENGERSERVER']._serialized_end=454
# @@protoc_insertion_point(module_scope)
